apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpe-api-servicemonitor
  labels:
    release: prometheus-operator # Standard enterprise label hook
spec:
  selector:
    matchLabels:
      app: hpe-api
  endpoints:
  - port: "8000" # Maps to the containerPort in our deployment
    path: /metrics
    interval: 10s
    scheme: http
