"""
dashboard/Home.py

Main landing page and entry point for the multi-page HPE Storage Control Plane console.
Coordinates backend api connections and showcases overall cluster layout.
"""

import time
import pandas as pd
import streamlit as st
from pathlib import Path
import sys

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from dashboard.utils import (
    apply_custom_css,
    get_api_data,
    can_autostart_backend,
    start_backend_api,
    wait_for_api,
    render_sidebar_telemetry
)

# Set page config
st.set_page_config(
    page_title="HPE Storage Control Plane",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Apply global custom styles
apply_custom_css()

# API autostart logic
health = get_api_data("/health", timeout=1.0)
if not health:
    if can_autostart_backend() and not st.session_state.get("backend_autostart_attempted"):
        st.session_state["backend_autostart_attempted"] = True
        started = start_backend_api()
        if started:
            with st.spinner("Starting local FastAPI control plane on port 8000..."):
                health = wait_for_api(seconds=60.0)
        if health:
            st.rerun()

# Render sidebar state
health_status = render_sidebar_telemetry()

# If API is not reachable, display startup instructions
if not health_status:
    st.error("Backend Control Plane API is unreachable on port 8000.")
    st.info("The FastAPI control plane must be started to fetch telemetry.")
    st.code("python -m uvicorn api.main:app --host 127.0.0.1 --port 8000", language="bash")
    st.code("python scripts/telemetry_playback.py", language="bash")
    
    if st.session_state.get("last_api_error"):
        st.caption(f"Last API connection error: {st.session_state['last_api_error']}")
    if st.session_state.get("backend_autostart_error"):
        st.caption(f"Auto-start failed: {st.session_state['backend_autostart_error']}")
        
    st.warning("Retrying API connection in 5 seconds...")
    time.sleep(5)
    st.rerun()

# --- Main Landing Page Visual Elements ---
st.markdown("<h1>⚡ HPE Storage Control Plane</h1>", unsafe_allow_html=True)
st.markdown(
    "Welcome to the **HPE Intelligent Storage Decision Engine**. This console coordinates "
    "real-time IO workload profiling, hotspot mitigation, tail latency forecasts, and rebalancing controllers "
    "across storage nodes.",
    unsafe_allow_html=True
)

st.markdown("---")

col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Console Architecture & Pages")
    st.markdown("""
    Select a module from the sidebar navigation menu to analyze cluster behaviors:
    
    1. **⚡ Cluster Overview**:
       - View high-level metrics (Average Latency, Aggregate IOPS, Rollbacks, and Rebalances).
       - Live telemetry view using lightweight `@st.fragment` containers.
       - A high-density active volumes list with integrated inline SVG sparklines.
       - Cluster-wide prescriptive recommendations for automated QoS, re-tiering, and job rescheduling.
       
    2. **🔍 Hotspot & Diagnostics**:
       - Deep dive into volume classifications and attribution details.
       - Local model explainability with SHAP impact attributions.
       - Topographical shared storage network mapping.
       - Noisy Neighbor aggressor detection.
       
    3. **🔮 Forecasting & Headroom**:
       - Days-to-Fill (DTF) estimations generated by N-BEATS deep learning capacity forecasts.
       - TFT-driven multi-quantile 24h tail latency performance projections.
       
    4. **🛠️ Rebalancing & Policies**:
       - Configure rebalancer policies (activation limits, action rates, safety bounds).
       - Evaluate active actuators (CSI node affinity updates, REST-based Array APIs) and monitor states.
       - Trigger manual volume migrations or execute rollbacks.
       - Capacity What-If scenarios simulator.
    """)

with col2:
    st.subheader("Cluster Status Overview")
    
    # Render quick statistics
    kpi_data = get_api_data("/kpi") or {}
    volumes_list = get_api_data("/volumes") or []
    
    live_vol_count = kpi_data.get("live_volume_count", 0)
    current_tick = kpi_data.get("current_tick")
    avg_lat = kpi_data.get("avg_latency_us", 0.0)
    
    st.markdown(f"""
    <div class="metric-card">
        <div class="metric-title">Active Control Plane</div>
        <div class="metric-value" style="color: #00e676;">HEALTHY</div>
        <div class="metric-subtitle">API Port: 8000 (Connected)</div>
    </div>
    <div class="metric-card">
        <div class="metric-title">Managed Volumes</div>
        <div class="metric-value">{len(volumes_list)} / {live_vol_count}</div>
        <div class="metric-subtitle">Active Volumes Profiled</div>
    </div>
    <div class="metric-card">
        <div class="metric-title">System-wide Latency</div>
        <div class="metric-value">{avg_lat:.1f} µs</div>
        <div class="metric-subtitle">Cluster Average</div>
    </div>
    """, unsafe_allow_html=True)
